Shop/Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('userprofile.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/userprofile/urls.py
from .views import UserProfileView, UserAddressView, ChangePasswordView
from django.urls import path
app_name = 'profile'


urlpatterns = [
    path('profile/<pk>/', UserProfileView.as_view(), name='profile'),
    path('profile/<pk>/address/', UserAddressView.as_view(), name='user_address'),
    path('profile/<pk>/change_password/', ChangePasswordView.as_view(), name='change_password'),

]

Shop/userprofile/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_countries.fields import CountryField

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE, related_name='profile_set')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    image = models.ImageField(null=True, default='profile/default.jpg', upload_to='profile/')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Address(models.Model):
    country = CountryField()
    region = models.CharField(max_length=255, )
    city = models.CharField(max_length=255, )
    street = models.CharField(max_length=255, )
    index = models.CharField(max_length=15, )
    recipient = models.CharField('full name', max_length=255, )
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='address_set')
    objects = models.Manager()

    def __str__(self):
        return "{country} - {city}".format(country=self.country, city=self.city)

Shop/userprofile/forms.py
from allauth.account.forms import SetPasswordForm, ChangePasswordForm
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

from .models import Address
from django_countries.widgets import CountrySelectWidget


class UserAddressForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.user = kwargs.get('user')
        # print(self.user)

    city = forms.CharField(widget=forms.TextInput({
        'placeholder': 'city',
        'class': 'form-control'
    }))

    region = forms.CharField(widget=forms.TextInput({
        'placeholder': 'region',
        'class': 'form-control'
    }))

    street = forms.CharField(widget=forms.TextInput({
        'placeholder': 'street',
        'class': 'form-control'
    }))

    index = forms.CharField(widget=forms.TextInput({
        'placeholder': 'index',
        'class': 'form-control'
    }))

    recipient = forms.CharField(widget=forms.TextInput({
        'placeholder': 'recipient',
        'class': 'form-control'
    }))

    class Meta:
        model = Address
        exclude = ('profile', )
        widgets = {'country': CountrySelectWidget()}

    def save(self, commit=True):
        # self.cleaned_data['profile'] = self.user.profile_set
        self.cleaned_data['profile_id'] = self.initial['profile_id']
        print(self.cleaned_data)
        return Address.objects.create(**self.cleaned_data)


class ChangePassword(ChangePasswordForm):
    pass

Shop/userprofile/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView
from .forms import UserAddressForm, ChangePassword
from allauth.account.views import PasswordChangeView

User = get_user_model()


class UserProfileView(DetailView):
    template_name = 'userprofile/index.html'

    def get_queryset(self):
        return User.objects.all().select_related('profile_set').prefetch_related('profile_set__address_set')

    def get_context_data(self, **kwargs):
        context = {
            'profile': self.get_object(),
            'address_form': UserAddressForm(),
            'change_password_form': ChangePassword(user=self.get_object())
        }
        return context


class UserAddressView(CreateView):

    template_name = 'userprofile/index.html'

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        print(user)
        print(kwargs)
        print(request.POST)
        form = UserAddressForm(data=request.POST, )
        if form.is_valid():
            form.save()
        print(form.errors)
        return redirect('profile:profile', pk=kwargs.get('pk'))

    def get_queryset(self):
        return User.objects.all().select_related('profile_set').prefetch_related('profile_set__address_set')

    def get_form_kwargs(self):
        data = super().get_form_kwargs()
        data['user'] = self.get_object()
        return data


class ChangePasswordView(PasswordChangeView):
    #template_name = "account/password_change." + app_settings.TEMPLATE_EXTENSION
    form_class = ChangePassword

    def get_success_url(self):
        return reverse_lazy('profile:profile', kwargs={'pk': self.kwargs.get('pk')})

Shop/userprofile/templates/userprofile/index.html
{% load countries %}
{% get_countries as countries%}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<hr>
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1>{{ profile.username }}</h1></div>
    	<div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div>
    </div>
    <div class="row">
  		<div class="col-sm-3"><!--left col-->


      <div class="text-center">
        <img src="{{ profile.profile_set.image.url }}" class="avatar img-circle img-thumbnail" alt="avatar">
        <h6>Upload a different photo...</h6>
        <input type="file" class="text-center center-block file-upload">
      </div></hr><br>


          <div class="panel panel-default">
            <div class="panel-heading">Website <i class="fa fa-link fa-1x"></i></div>
            <div class="panel-body"><a href="http://bootnipets.com">bootnipets.com</a></div>
          </div>


          <ul class="list-group">
            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Shares</strong></span> 125</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> 13</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Posts</strong></span> 37</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Followers</strong></span> 78</li>
          </ul>

          <div class="panel panel-default">
            <div class="panel-heading">Social Media</div>
            <div class="panel-body">
            	<i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
            </div>
          </div>

        </div><!--/col-3-->
    	<div class="col-sm-9">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
                <li><a data-toggle="tab" href="#messages">Menu 1</a></li>
                <li><a data-toggle="tab" href="#settings">Menu 2</a></li>
              </ul>


          <div class="tab-content">
            <div class="tab-pane active" id="home">
                <hr>
                  <form class="form" action="##" method="post" id="registrationForm">
                      <div class="form-group">

                          <div class="col-xs-6">
                              <label for="first_name"><h4>First name</h4></label>
                              <input type="text" class="form-control" name="first_name" id="first_name" placeholder=" {% if  profile.first_name %} {{ profile.first_name }} {% else %} first name {% endif %}" title="enter your first name if any.">
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                            <label for="last_name"><h4>Last name</h4></label>
                              <input type="text" class="form-control" name="last_name" id="last_name" placeholder="{% if  profile.last_name %} {{ profile.last_name }} {% else %} last name {% endif %}" title="enter your last name if any.">
                          </div>
                      </div>

                      <div class="form-group">
                          <div class="col-xs-6">
                             <label for="mobile"><h4>Mobile</h4></label>
                              <input type="text" class="form-control" name="mobile" id="mobile" placeholder="enter mobile number" title="enter your mobile number if any.">
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                              <label for="email"><h4>Email</h4></label>
                              <input type="email" class="form-control" name="email_address" id="email_address" placeholder="email address" title="enter your email.">
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                              <label for="email"><h4>Location</h4></label>
                              <select class="form-control">
                                  {% for country in countries %}
                                  <option value="{{ country.code }}">
                                      {{ country.name }}
                                  </option>
                                  {% endfor %}

                              </select>
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                              <label for="password"><h4>Password</h4></label>
                              <input type="password" class="form-control" name="password" id="password" placeholder="password" title="enter your password.">
                          </div>
                      </div>
                      <div class="form-group">

                          <div class="col-xs-6">
                            <label for="password2"><h4>Verify</h4></label>
                              <input type="password" class="form-control" name="password2" id="password2" placeholder="password2" title="enter your password2.">
                          </div>
                      </div>
                      <div class="form-group">
                           <div class="col-xs-12">
                                <br>
                              	<button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Save</button>
                               	<button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button>
                            </div>
                      </div>
              	</form>

              <hr>

             </div><!--/tab-pane-->
             <div class="tab-pane" id="messages">

               <h2></h2>

               <hr>

                  <form class="form" action="{% url 'profile:change_password' pk=user.id %}" method="post" id="registrationForm">
                      {% csrf_token %}
                     {% for field in change_password_form %}
                      <div class="form-group">
                            <div class="col-xs-6">
                            <label for="{{field.label}}"><h4>{{field.label}}</h4></label>
                                {{field}}
                          </div>
                      </div>
                      {% endfor %}


                      <div class="form-group">
                           <div class="col-xs-12">
                                <br>
                              	<button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Save</button>
                               	<button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button>
                            </div>
                      </div>
              	</form>

             </div><!--/tab-pane-->
             <div class="tab-pane" id="settings">


                  <hr>
                  <form class="form" action="{% url 'profile:user_address' pk=user.id %}" method="post" id="registrationForm">
                      {% csrf_token %}
                      {% for field in address_form %}
                      <div class="form-group">
                            <div class="col-xs-6">
                            <label for="{{field.label}}"><h4>{{field.label}}</h4></label>
                                {{field}}
                          </div>
                      </div>
                      {% endfor %}
                      <input type="hidden" name="profile_id" value="{{ user.profile_set.id}}">
                      <div class="form-group">
                           <div class="col-xs-12">
                                <br>
                              	<button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Save</button>

                            </div>
                      </div>

                  </form>
              </div>

              </div><!--/tab-pane-->
          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div><!--/row-->