Shop/Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('userprofile.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/cart/urls.py
from django.urls import path

from .views import ProductInCart

app_name = 'cart'


urlpatterns = [
    path('carts/', ProductInCart.as_view())

]

Shop/mainapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BaseView.as_view(), name='base'),
    path('products/<str:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug>/', views.DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', views.ChangeQTYView.as_view(), name='change_qty'),
    path('signup/', views.UserSignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('login/', views.UserSignInView.as_view(), name='login'),
 #   path('email/', views.SendEmailView.as_view(), name='login'),

]

Shop/order/urls.py
from django.urls import path
from .views import CreateOrderView
app_name = 'order'

urlpatterns = [
    path('order/create/', CreateOrderView.as_view(), name='create')

]

Shop/cart/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

User = get_user_model()


class Cart(models.Model):

    owner = models.OneToOneField(User, null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField('CartProduct', blank=True, related_name='related_cart')
    # total_products = models.PositiveIntegerField(default=0)
    # final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        # cart_data = self.products.aggregate(models.Sum('final_price'), models.Count('id'))
        # if cart_data.get('final_price__sum'):
        #     self.final_price = cart_data['final_price__sum']
        # else:
        #     self.final_price = 0
        # self.total_products = cart_data['id__count']
        super().save(*args, **kwargs)


class CartProduct(models.Model):

    user = models.ForeignKey(User, verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)

Shop/mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify


User = get_user_model()


class MinResolutionErrorException(Exception):

    pass


class MaxResolutionErrorException(Exception):

    pass


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:

    objects = LatestProductsManager()


class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Товар ': 'prod1__count',
    }

    def get_queryset(self):
        return super().get_queryset()


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


def validate_image(img):
    min_height, min_width = Product.MIN_RESOLUTION
    max_height, max_width = Product.MAX_RESOLUTION
    if img.height < min_height or img.width < min_width:
        raise MinResolutionErrorException('Разрешение изображения меньше минимального!')
    if img.height > max_height or img.width > max_width:
        raise MaxResolutionErrorException('Разрешение изображения больше максимального!')


class Product(models.Model):

    MIN_RESOLUTION = (40, 40)
    MAX_RESOLUTION = (800, 800)
    MAX_IMAGE_SIZE = 3145728

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE, related_name='product_set')
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True, allow_unicode=True)
    image = models.ImageField(verbose_name='Изображение', validators=(validate_image,))
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    objects = models.Manager()

    def __str__(self):
        return self.title

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return reverse_lazy('product_detail', kwargs={'slug': self.slug})

    def get_model_name(self):
        return self.__class__._meta.model_name

    def save(self, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        return super().save(**kwargs)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)

Shop/mainapp/forms.py
from allauth.account.forms import SignupForm, LoginForm, PasswordField
from django import forms


class UserSignupForm(SignupForm):
    pass


class UserSignInForm(LoginForm):
    password = PasswordField(
        required=True,
        label="Password",
        autocomplete="current-password",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password',

        }))

Shop/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View

from mainapp.models import LatestProducts


class ProductInCart(View):

    def get(self, request, *args, **kwargs):
        # # categories = Category.objects.get_categories_for_left_sidebar()
        # products = LatestProducts.objects.get_products_for_main_page(
        #     # 'prod1', 'prod2', with_respect_to='prod1'
        # )
        # context = {
        #     # 'categories': categories,
        #     'products': products,
        #     'cart': self.cart
        # }
        request.session['cart'] = 'fsrergrfg'
        request.session['cart1'] = 'fsrergrfg'
        print(request.session.items())
        return render(request, 'base.html', {})

Shop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, View
from .models import Product, Category, LatestProducts, Customer
from .mixins import CategoryDetailMixin, CartMixin
from django.http import HttpResponseRedirect
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from allauth.account.views import SignupView, LoginView
from .forms import UserSignupForm, UserSignInForm
from django.core.mail import send_mail
from cart.models import Cart, CartProduct
from cart.cart import Cart as SessionCart


class BaseView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        context = {
            'products': products,
            'cart': self.cart
        }
        return render(request, 'index.html', context)


class ProductDetailView(CategoryDetailMixin, DetailView):

    CT_MODEL_MODEL_CLASS = {
        'prod1': Product
    }
    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        return Product.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CategoryDetailView(DetailView):

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['category_products'] = Product.objects.filter(category=self.get_object())
        category = self.get_object()
        context['category_products'] = category.product_set.all()
        return context


class CartView(View):

    def get(self, request, *args, **kwargs):
        cart = SessionCart(request)
        context = {
            'cart': cart
        }
        return render(request, 'cart.html', context)


class AddToCartView(View):

    def post(self, request, *args, **kwargs):

        qty = request.POST.get('qty')
        product = self.get_object()
        print(qty)
        cart = SessionCart(request)
        cart.add(product_id=product.id, qty=qty)
        print(request.session.items())
        messages.add_message(request, messages.INFO, "Товар успешно добавлен")
        return HttpResponseRedirect('/cart/')

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs.get('slug'))


class DeleteFromCartView(View):

    def get(self, request, slug, *args, **kwargs):
        # ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        # content_type = ContentType.objects.get(model=ct_model)
        # product = content_type.model_class().objects.get(slug=product_slug)
        # cart_product = CartProduct.objects.get(
        #     user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        # )
        # self.cart.products.remove(cart_product)
        # cart_product.delete()
        # self.cart.save()
        product = self.get_object()
        cart = SessionCart(request)
        cart.delete(product_id=product.id)
        messages.add_message(request, messages.INFO, "Товар успешно удален")
        return HttpResponseRedirect('/cart/')

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs.get('slug'))


class ChangeQTYView(View):

    def post(self, request, *args, **kwargs):
        # cart_product = CartProduct.objects.get(
        #     user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        # )
        # qty = int(request.POST.get('qty'))
        # cart_product.qty = qty
        # cart_product.save()
        # self.cart.save()
        product = self.get_object()
        cart = SessionCart(request)
        cart.update(product_id=product.id, qty=request.POST.get('qty'))
        messages.add_message(request, messages.INFO, "Кол-во успешно изменено")
        return HttpResponseRedirect('/cart/')

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs.get('slug'))


class UserSignUpView(SignupView):

   form_class = UserSignupForm
   template_name = 'account/signup.html'


class UserSignInView(LoginView):

   form_class = UserSignInForm
   template_name = 'account/login2.html'


class SendEmailView(View):

    def get(self, request, **kwargs):
        subject = 'Hello'
        message = 'Alexander'
        recipients = (
            'alexsilin1997@gmail.com',
            # 'bandirom@ukr.net'

        )
        email_from='alexsilin1997@gmail.com'
        send_mail(subject=subject, message=message, recipient_list=recipients, from_email=email_from)
        return render(request, template_name='base.html')

Shop/mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
  (function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'white')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

Shop/mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% block above_head %}
{% endblock above_head %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">
{% block head %}
    {% endblock head %}
</head>
<style>
  body {
  padding-top: 56px;
}

</style>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap. Hello {{ user.username }} </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li>{% include 'loginpartial.html' %}</li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Shop Name</h1>
            <div class="list-group">
                {% for category in categories %}
                <a href="{{ category.url }}" class="list-group-item">{{ category.name }} ({{ category.count }})</a>
                {% endfor %}

            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
            {% block content %}
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}"
                                                                      alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                            </h4>
                            <h5>{{ product.price }} руб.</h5>
                            <form action="{% url 'add_to_cart'  slug=product.slug %}" method="post">
                                {% csrf_token %}
                                <div><input type="number" class="form-control" value="1" min="1" name="qty"></div>
                                <button class="btn btn-danger">Добавить в корзину</button>
                            </form>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- /.row -->
            {% endblock content %}
        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

Shop/mainapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Ваша корзина</h3>
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}

<table class="table">
    <thead>
    <tr>
        <th scope="col">Наименование</th>
        <th scope="col">Изображение</th>
        <th scope="col">Цена</th>
        <th scope="col">Количество</th>
        <th scope="col">Общая цена</th>
        <th scope="col">Действие</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <th scope="row"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></th>
        <td class="w-25"><img src="{{ product.image.url }}" class="img-fluid"></td>
        <td>{{ product.price }} руб.</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.total_price }} руб.</td>
        <td>
            <form action="{% url 'change_qty' slug=product.slug %}"
                  method="POST">
                {% csrf_token %}
                <input type="number" class="form-control" name="qty" style="width: 70px;" min="1"
                       value="{{ item.quantity }}">
                <br>
                <input type="submit" class="btn btn-primary" value="Изменить кол-во">
            </form>

            <a href="{% url 'delete_from_cart' slug=product.slug %}">
                <button class="btn btn-danger">Удалить из корзины</button>

            </a>


        </td>

    </tr>

    {% endwith %}
    {% endfor %}

    <tr>
        <td colspan="2"></td>
        <td>Итого:</td>
        <td>{{ cart|length }}</td>
        <td><strong>{{ cart.get_final_price }} руб.</strong></td>
        <a href="{% url 'order:create' %}">
            <button class="btn btn-danger">Оформить заказ</button>
        </a>

    </tr>

    </tbody>
</table>

{% endblock content %}

Shop/mainapp/templates/category_detail.html
{% extends 'base.html' %}


{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
     <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item active">{{ category.name }}</li>

  </ol>
</nav>

 <div class="row">
          {% for product in category_products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} руб.</h5>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

{% endblock content %}

Shop/mainapp/templates/index.html
{% extends 'base.html' %}

Shop/mainapp/templates/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="{% url 'logout' %}" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">
            {% if user.is_staff %}
            <a target="_blank" style="text-decoration: none" href="{% url 'admin:index' %}"> Hello {{ user.username }}!</a>
            {% else %}
                Hello {{ user.username }}!
            {% endif %}

        </span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
</form>

{% else %}

    <li><a href="{% url 'login' %}">Sign in</a></li>
    <li><a href="{% url 'signup' %}">Sign up</a></li>

{% endif %}

Shop/mainapp/templates/prod1_specification.html
<table class="table">
  <tbody>
  <tr>
      <td>Характеристика 1</td>
      <td>{{ product.spec1 }}</td>
    </tr>
      <tr>
      <td>Характеристика 2</td>
      <td>{{ product.spec2 }}</td>
    </tr>
      <tr>
      <td>Характеристика 3</td>
      <td>{{ product.spec3 }}</td>
    </tr>
  </tbody>
</table>

Shop/mainapp/templates/prod2_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Характеристика 1</td>
      <td>{{ product.spec1 }}</td>
    </tr>
      <tr>
      <td>Характеристика 2</td>
      <td>{{ product.spec2 }}</td>
    </tr>
      <tr>
      <td>Характеристика 3</td>
      <td>{{ product.spec3 }}</td>
    </tr>
  </tbody>
</table>

Shop/mainapp/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
     <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }} руб.</p>
         <p>Описание: {{ product.description }}</p>
        <hr>
        <form action="{% url 'add_to_cart'  slug=product.slug %}" method="post">
            {% csrf_token %}
            <input type="number" value="1" min="1" name="qty">
            <button class="btn btn-danger">Добавить в корзину</button>
        </form>
        <form action="{% url 'delete_from_cart'  slug=product.slug %}" method="post">
            {% csrf_token %}
            <input type="number" value="1" min="1" name="qty">
            <button class="btn btn-danger">Удалить из корзины</button>
        </form>

    </div>




</div>


{% endblock content %}